Rusa4ok.NET/Areas/Admin/Controllers/GalleryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Rusa4ok.NET;
using Rusa4ok.NET.Models;

namespace Rusa4ok.NET.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class GalleryController : Controller
    {
        private EFContext db = new EFContext();

        // GET: Admin/Gallery
        public ActionResult Index()
        {
            return View(db.GalleryModels.ToList());
        }

        // GET: Admin/Gallery/Create
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Title, ImgName")] GalleryModels galleryModels, HttpPostedFileBase upload)
        {

            if (upload != null)
            {
                string fileName = System.IO.Path.GetFileName(upload.FileName);
                upload.SaveAs(Server.MapPath("~/images/gallery/" + fileName));

                galleryModels.ImgName = fileName;
            }

            if (ModelState.IsValid)
            {
                db.GalleryModels.Add(galleryModels);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(galleryModels);
        }

        // GET: Admin/Gallery/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GalleryModels galleryModels = db.GalleryModels.Find(id);
            if (galleryModels == null)
            {
                return HttpNotFound();
            }
            return View(galleryModels);
        }

        // POST: Admin/Gallery/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id, Title, ImgName")] GalleryModels galleryModels, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {

                string fileName = System.IO.Path.GetFileName(upload.FileName);
                upload.SaveAs(Server.MapPath("~/images/gallery/" + fileName));

                galleryModels.ImgName = fileName;
                db.Entry(galleryModels).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(galleryModels);
        }

        // GET: Admin/Gallery/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GalleryModels galleryModels = db.GalleryModels.Find(id);
            if (galleryModels == null)
            {
                return HttpNotFound();
            }
            return View(galleryModels);
        }

        // POST: Admin/Gallery/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            GalleryModels galleryModels = db.GalleryModels.Find(id);
            db.GalleryModels.Remove(galleryModels);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Rusa4ok.NET/Areas/Admin/Views/Gallery/Create.cshtml
@model Rusa4ok.NET.Models.GalleryModels

@{
    ViewBag.Title = String.Format("Создание элемента - Галерея");
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<section class="body-content">
    <div class="container">
        <div class="block-header">
            <h2>Просмотр и редактирование галереи</h2>
        </div>
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">

                    @using (Html.BeginForm("Create", "Gallery", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()

                        <div class="card-body">

                            @if (ViewData.ModelState.Keys.Any(k => ViewData.ModelState[k].Errors.Any()))
                            {
                                <div class="form-group">
                                    <div class="alert alert-danger">@Html.ValidationSummary(false, "Ошибки: ")</div>
                                </div>
                            }

                            @Html.HiddenFor(model => model.Id)

                            <div class="form-group">
                                @Html.LabelFor(model => model.Title)
                                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                            </div>

                            <div class="form-group">
                                <label for="photo">Фото</label>
                                <input type="file" class="form-control-file" id="photo" name="upload">
                                @Html.HiddenFor(Model => Model.ImgName, new { id = "hfPhoto" })
                            </div>

                            <div class="form-group">
                                <img id="imgPreview" class="img-fluid" />
                            </div>

                            <div class="form-group">
                                <button type="submit" class="btn btn-primary w-100">Создать</button>
                            </div>

                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</section>

@section Scripts{
    <script>
        $('#photo').change(function () {
            if (this.files[0]) {

                $('#hfPhoto').val(this.files[0].name);

                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#imgPreview').attr('src', e.target.result);
                }

                reader.readAsDataURL(this.files[0]); // convert to base64 string
            }

        });
    </script>
}

Rusa4ok.NET/Areas/Admin/Views/Gallery/Delete.cshtml
@model Rusa4ok.NET.Models.GalleryModels

@{
    ViewBag.Title = String.Format("Удаление {0} - Галерея", Model.Title);
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<section class="body-content">
    <div class="container">
        <div class="block-header">
            <h2>Удаление фото</h2>
        </div>
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">

                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="card-body">

                            @if (@ViewData.ModelState.Keys.Any(k => ViewData.ModelState[k].Errors.Any()))
                            {
                                <div class="form-group">
                                    <div class="alert alert-danger">@Html.ValidationSummary(false, "Ошибки: ")</div>
                                </div>
                            }

                            @Html.HiddenFor(model => model.Id)

                            <div class="form-group">
                                @Html.LabelFor(model => model.Title)
                                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
                            </div>

                            @Html.HiddenFor(Model => Model.ImgName, new { id = "hfPhoto" })

                            <div class="form-group">
                                <label for="photo">Фото</label>
                                <img id="imgPreview" class="img-fluid" src="@Url.Content(String.Format("~/images/gallery/{0}", Model.ImgName))" />
                            </div>

                            <div class="form-group">
                                <button type="submit" class="btn btn-primary w-100" onclick="return confirm('Уверены?')">Удалить</button>
                            </div>

                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</section>

Rusa4ok.NET/Areas/Admin/Views/Gallery/Edit.cshtml
@model Rusa4ok.NET.Models.GalleryModels

@{
    ViewBag.Title = String.Format("Редактирование {0} - Галерея", Model.Title);
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<section class="body-content">
    <div class="container">
        <div class="block-header">
            <h2>Редактирование фото</h2>
        </div>
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">

                    @using (Html.BeginForm("Edit", "Gallery", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()

                    <div class="card-body">

                        @if (@ViewData.ModelState.Keys.Any(k => ViewData.ModelState[k].Errors.Any()))
                        {
                            <div class="form-group">
                                <div class="alert alert-danger">@Html.ValidationSummary(false, "Ошибки: ")</div>
                            </div>
                        }

                        @Html.HiddenFor(model => model.Id)

                        <div class="form-group">
                            @Html.LabelFor(model => model.Title)
                            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                        </div>

                        <div class="form-group">
                            <label for="photo">Фото</label>
                            <input type="file" class="form-control-file" id="photo" name="upload">
                            @Html.HiddenFor(Model => Model.ImgName, new { id = "hfPhoto" })
                        </div>

                        <div class="form-group">
                            <img id="imgPreview" class="img-fluid" src="@Url.Content(String.Format("~/images/gallery/{0}", Model.ImgName))" />
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-primary w-100">Сохранить</button>
                        </div>

                    </div>
                    }
                </div>
            </div>
        </div>
    </div>
</section>

@section Scripts{
    <script>
        $('#photo').change(function () {
            if (this.files[0]) {

                $('#hfPhoto').val(this.files[0].name);

                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#imgPreview').attr('src', e.target.result);
                }

                reader.readAsDataURL(this.files[0]); // convert to base64 string
            }

        });
    </script>
}

Rusa4ok.NET/Areas/Admin/Views/Gallery/Index.cshtml
@model IEnumerable<Rusa4ok.NET.Models.GalleryModels>

@{
    ViewBag.Title = "Галерея";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<section class="body-content">
    <div class="container">
        <div class="block-header">
            <h2>Просмотр и редактирование галереи</h2>
        </div>
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="body table-responsive">
                        <div class="header">
                            <h2>Таблица галереи</h2>
                            <ul class="header-dropdown m-r--5">
                                <li class="dropdown">
                                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                        <i class="fas fa-chevron-circle-down"></i>
                                    </a>
                                    <ul class="dropdown-menu pull-right">
                                        <li>@Html.ActionLink("Добавить фото", "Create", null, new { @class = "waves-effect waves-block" })</li>
                                    </ul>
                                </li>
                            </ul>
                        </div>

                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>@Html.DisplayNameFor(model => model.Title)</th>
                                    <th>Редактировать</th>
                                    <th>Удалить</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@Html.DisplayFor(modelItem => item.Title)</td>
                                        <td>@Html.ActionLink("Редактировать", "Edit", new { id = item.Id })</td>
                                        <td>@Html.ActionLink("Удалить", "Delete", new { id = item.Id })</td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>