Rusa4ok.NET/Models/Order.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Rusa4ok.NET.Models
{
    public partial class Order
    {
        public int Id { get; set; }

        [Required]
        [Display(Name = "Название")]
        [StringLength(128)]
        public string Name { get; set; }

        [Required]
        [Display(Name = "Описание")]
        public string Description { get; set; }

        [Required]
        [StringLength(128)]
        public string ImgName { get; set; }

        public decimal Cost { get; set; }

        public DateTime? CreateDate { get; set; }

        public int CategoryId { get; set; }

        public virtual Category Category { get; set; }
    }

    public partial class Category
    {
        public int Id { get; set; }

        [Display(Name = "Название")]
        [StringLength(128)]
        public string Name { get; set; }

        [Required]
        [StringLength(128)]
        public string ImgName { get; set; }

        public virtual List<Order> Orders { get; set; }
    }
}

Rusa4ok.NET/Areas/Admin/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Rusa4ok.NET;
using Rusa4ok.NET.Models;

namespace Rusa4ok.NET.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class OrderController : Controller
    {
        private EFContext db = new EFContext();

        public ActionResult Index()
        {
            return View(db.Order.ToList());
        }

        public ActionResult Create()
        {
            var ListOfCategories = new SelectList(db.Category.ToList(), "ID", "Name");
            ViewBag.Categories = ListOfCategories;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Name, CategoryId, Description, ImgName")] Order order, HttpPostedFileBase upload)
        {

            if (upload != null)
            {
                string fileName = System.IO.Path.GetFileName(upload.FileName);
                upload.SaveAs(Server.MapPath("~/images/orders/" + fileName));

                order.ImgName = fileName;
            }

            if (ModelState.IsValid)
            {
                order.CreateDate = DateTime.Now;
                db.Order.Add(order);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(order);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Order.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            var ListOfCategories = new SelectList(db.Category.ToList(), "ID", "Name", order.CategoryId);
            ViewBag.Categories = ListOfCategories;
            return View(order);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id, Name, Description, ImgName")] Order order, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {

                string fileName = System.IO.Path.GetFileName(upload.FileName);
                upload.SaveAs(Server.MapPath("~/images/orders/" + fileName));

                order.ImgName = fileName;
                db.Entry(order).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(order);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Order.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            var ListOfCategories = new SelectList(db.Category.ToList(), "ID", "Name", order.CategoryId);
            ViewBag.Categories = ListOfCategories;
            return View(order);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Order order = db.Order.Find(id);
            db.Order.Remove(order);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Rusa4ok.NET/Areas/Admin/Views/Order/Create.cshtml
@model Rusa4ok.NET.Models.Order

@{
    ViewBag.Title = String.Format("Создание элемента - Товары");
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<section class="body-content">
    <div class="container">
        <div class="block-header">
            <h2>Просмотр и редактирование товаров</h2>
        </div>
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">

                    @using (Html.BeginForm("Create", "Order", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()

                    <div class="card-body">

                        @if (ViewData.ModelState.Keys.Any(k => ViewData.ModelState[k].Errors.Any()))
                        {
                            <div class="form-group">
                                <div class="alert alert-danger">@Html.ValidationSummary(false, "Ошибки: ")</div>
                            </div>
                        }

                        <div class="form-group">
                            @Html.LabelFor(model => model.Name)
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Description)
                            @Html.TextAreaFor(model => model.Description,  new { @class = "form-control" })
                        </div>

                        <div class="form-group">
                            @Html.DropDownListFor(model => model.CategoryId, (IEnumerable<SelectListItem>)ViewBag.Categories, new { @class = "form-control" })
                        </div>

                        <div class="form-group">
                            <label for="photo">Фото</label>
                            <input type="file" class="form-control-file" id="photo" name="upload">
                            @Html.HiddenFor(Model => Model.ImgName, new { id = "hfPhoto" })
                        </div>

                        <div class="form-group">
                            <img id="imgPreview" class="img-fluid" />
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-primary w-100">Создать</button>
                        </div>

                    </div>
                    }
                </div>
            </div>
        </div>
    </div>
</section>

@section Scripts{
    <script>
        $('#photo').change(function () {
            if (this.files[0]) {

                $('#hfPhoto').val(this.files[0].name);

                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#imgPreview').attr('src', e.target.result);
                }

                reader.readAsDataURL(this.files[0]); // convert to base64 string
            }

        });
    </script>
}

Rusa4ok.NET/Areas/Admin/Views/Order/Delete.cshtml
@model Rusa4ok.NET.Models.Order

@{
    ViewBag.Title = String.Format("Удаление {0} - Товары", Model.Name);
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<section class="body-content">
    <div class="container">
        <div class="block-header">
            <h2>Удаление товара</h2>
        </div>
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">

                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                    <div class="card-body">

                        @if (@ViewData.ModelState.Keys.Any(k => ViewData.ModelState[k].Errors.Any()))
                        {
                            <div class="form-group">
                                <div class="alert alert-danger">@Html.ValidationSummary(false, "Ошибки: ")</div>
                            </div>
                        }

                        @Html.HiddenFor(model => model.Id)

                        <div class="form-group">
                            @Html.LabelFor(model => model.Name)
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Description)
                            @Html.TextAreaFor(model => model.Description, new { @class = "form-control", disabled = "disabled" })
                        </div>

                        <div class="form-group">
                            @Html.DropDownListFor(model => model.CategoryId, (IEnumerable<SelectListItem>)ViewBag.Categories, new { @class = "form-control", disabled = "disabled" })
                        </div>

                        @Html.HiddenFor(Model => Model.ImgName, new { id = "hfPhoto" })

                        <div class="form-group">
                            <label for="photo">Фото</label>
                            <img id="imgPreview" class="img-fluid" src="@Url.Content(String.Format("~/images/orders/{0}", Model.ImgName))" />
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-primary w-100" onclick="return confirm('Уверены?')">Удалить</button>
                        </div>

                    </div>
                    }
                </div>
            </div>
        </div>
    </div>
</section>

Rusa4ok.NET/Areas/Admin/Views/Order/Edit.cshtml
@model Rusa4ok.NET.Models.Order

@{
    ViewBag.Title = String.Format("Редактирование {0} - Товары", Model.Name);
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<section class="body-content">
    <div class="container">
        <div class="block-header">
            <h2>Редактирование товара</h2>
        </div>
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">

                    @using (Html.BeginForm("Edit", "Order", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()

                    <div class="card-body">

                        @if (@ViewData.ModelState.Keys.Any(k => ViewData.ModelState[k].Errors.Any()))
                        {
                            <div class="form-group">
                                <div class="alert alert-danger">@Html.ValidationSummary(false, "Ошибки: ")</div>
                            </div>
                        }

                        @Html.HiddenFor(model => model.Id)

                        <div class="form-group">
                            @Html.LabelFor(model => model.Name)
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Description)
                            @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
                        </div>

                        <div class="form-group">
                            @Html.DropDownListFor(model => model.CategoryId, (IEnumerable<SelectListItem>)ViewBag.Categories, new { @class = "form-control" })
                        </div>

                        <div class="form-group">
                            <label for="photo">Фото</label>
                            <input type="file" class="form-control-file" id="photo" name="upload">
                            @Html.HiddenFor(Model => Model.ImgName, new { id = "hfPhoto" })
                        </div>

                        <div class="form-group">
                            <img id="imgPreview" class="img-fluid" src="@Url.Content(String.Format("~/images/orders/{0}", Model.ImgName))" />
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-primary w-100">Сохранить</button>
                        </div>

                    </div>
                    }
                </div>
            </div>
        </div>
    </div>
</section>

@section Scripts{
    <script>
        $('#photo').change(function () {
            if (this.files[0]) {

                $('#hfPhoto').val(this.files[0].name);

                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#imgPreview').attr('src', e.target.result);
                }

                reader.readAsDataURL(this.files[0]); // convert to base64 string
            }

        });
    </script>
}

Rusa4ok.NET/Areas/Admin/Views/Order/Index.cshtml
@model IEnumerable<Rusa4ok.NET.Models.Order>

@{
    ViewBag.Title = "Товары";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<section class="body-content">
    <div class="container">
        <div class="block-header">
            <h2>Просмотр и редактирование товаров</h2>
        </div>
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="body table-responsive">
                        <div class="header">
                            <h2>Таблица товаров</h2>
                            <ul class="header-dropdown m-r--5">
                                <li class="dropdown">
                                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                        <i class="fas fa-chevron-circle-down"></i>
                                    </a>
                                    <ul class="dropdown-menu pull-right">
                                        <li>@Html.ActionLink("Добавить товаров", "Create", null, new { @class = "waves-effect waves-block" })</li>
                                    </ul>
                                </li>
                            </ul>
                        </div>

                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>@Html.DisplayNameFor(model => model.Name)</th>
                                    <th>@Html.DisplayNameFor(model => model.Description)</th>
                                    <th>Категория</th>
                                    <th>Редактировать</th>
                                    <th>Удалить</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@Html.DisplayFor(modelItem => item.Name)</td>
                                        <td>@Html.DisplayFor(modelItem => item.Description)</td>
                                        <td>@Html.DisplayFor(modelItem => item.Category.Name)</td>
                                        <td>@Html.ActionLink("Редактировать", "Edit", new { id = item.Id })</td>
                                        <td>@Html.ActionLink("Удалить", "Delete", new { id = item.Id })</td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>